version: "3"

services:
    app:
      build: .
      container_name: laravel_2
      volumes:
        - ./lara_prac:/var/www/html
      ports:
        - 8090:80
      depends_on:
        - db
    
    db:
      image: mysql:5.7
      volumes:
       - ./:/var/lib/mysql
      environment:
       - MYSQL_ROOT_PASSWORD=ikimono0308
       - MYSQL_DATABASE=laravel
       - MYSQL_USER=root
       - MYSQL_PASSWORD=root
      container_name: laravel_mysql_2
